server:
  port: 8100

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml  #mybatis配置文件所在路径
  type-aliases-package: com.zlsoft.framework.entites #所有Entity别名类所在包
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml               #mapper映射文件

spring:
  application:
    name: onecardinterface-admin-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource      #当前数据源操作类型
    driver-class-name: oracle.jdbc.driver.OracleDriver    #oracle驱动包
    url: jdbc:oracle:thin:@zlgysoft.cn:9095:orcl       #数据库名称
    username: zlhis
    password: his
    dbcp2:
      min-idle: 5                                     #数据库连接池的最小维持连接数
      initial-size: 5                                 #初始化连接数
      max-total: 5                                    #最大连接数
      max-wait-millis: 200                            #等待连接获取的最大超时时间


#配置项目热部署
  devtools:
    livereload:
      enabled: true

#eureka: #客户端注册进服务端
#  client:
#    service-url:
#      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
#  instance:
#    instance-id: microservicecloud-dept8001  #注册进Eureka Server服务的的的实例名称
#    prefer-ip-address: true #访问路径可以显示IP地址
#
#info:
#  app.name: zlsoft-microserviceclouds
#  company.name: www.zlsoft.com
#  build.artifactId: @project.artifactId@
#  build.version: @project.version@
